### ISSUE TITLE
BackUp files

### ISSUE THREAD

**Issue by DavidGarciaCat** [JPGSP/blog#10]
You should disable your IDE setting that creates a backup for all your files when you update them:

<img width="410" alt="screen shot 2018-02-22 at 21 53 11" src="https://user-images.githubusercontent.com/7809429/36566272-df0b84c4-181a-11e8-8b29-ccb2fb7d0b25.png">

- BackUp files should never be committed and pushed

- Given you're using Git it means you can revert a given commit to restore the previous information, so there is no need to keep a BackUp file.
  - The smaller and precise the commit, the easier to revert an update to recover the previous content

**Comment by JPGSP** [comment]
David, is it not possible that this issue is becase I was running the command php/app doctrine:schema:update --force more than one time, doing different entities backups?
Maybe, the best solution would be to write the follow rule in the gitignore:
*~

What do you think?

**Comment by DavidGarciaCat** [comment]
Hey @JPGSP 

Running `$ app/console | grep doctrine | grep update` you'll get just 1 SF command:
> `doctrine:schema:update`
>
> Executes (or dumps) the SQL needed to update the database schema to match the current mapping metadata.

If your Entities are updated because of this SF command then something is wrong, due the command should "execute" or "dump" the SQL but never "update" your entities.

I don't have a rule like `*~` neither on my project's `.gitignore` file nor on my global Git Ignore file and my entities are not updated in this way, with backup copies. This looks like a file that is auto-generated through your IDE. Which one are you using?

On the other hand, you could consider to use `Doctrine Migrations Bundle` that creates migration files instead of "hack" the database queries without control.

**Comment by DavidGarciaCat** [comment]
OK, let’s try what you suggested:

`*~`

Also, consider to review your Global Git Ignore based on these template files:

https://github.com/github/gitignore

And please consider to use Doctrine Migrations Bundle instead, it makes easier to maintain database updates on non-local environments

**Comment by JPGSP** [comment]
@DavidGarciaCat , the gitignore has been modified. The line which doesn´t commit the backup files is:
**/Entity/*~

**Comment by DavidGarciaCat** [comment]
When I need to look for just 1 line on a commit https://github.com/JPGSP/blog/commit/fd146692469e938c83f596fd9fe9ff72b1939cde that contains **43 additions** and **5 deletions** then the commit is wrong

Please refer to my other issue https://github.com/JPGSP/blog/issues/16

😄
