### ISSUE TITLE
Typos on Readme

### ISSUE THREAD

**Issue by DavidGarciaCat** [JPGSP/blog#12]
Current copy:

```
# Proyect Symfony 2.8 BLOG

Though this proyect I will build a blog base in the version 2.8 of Symfony framework.

Objective: Educational purpose
```

Typos:

- ~Proyect~ => Project
- ~Though~ => Through
- ~base~ => based

Should be like this:

```
# Symfony 2.8 project: Blog

Through this project I will build a blog based on Symfony 2.8.

Objective: Educational purpose
```

Be careful when writing, get some help through Google Translate (where basic typos fixes are suggested) and don't hesitate to use a spell checker

https://www.google.co.uk/search?q=spell+checker

😄

**Comment by DavidGarciaCat** [comment]
KISS Principle: keep it simple and straightforward

https://en.wikipedia.org/wiki/KISS_principle

**Comment by JPGSP** [comment]
👍🏻
