### ISSUE TITLE
❓ Query: what is the purpose?

### ISSUE THREAD

**Issue by DavidGarciaCat** [JPGSP/blog#18]
Hey there,

What is the purpose of this commit? https://github.com/JPGSP/blog/commit/cc9ebc70f14dc717685137942f9be5853f93a5cb

Neither the commit title nor the commit description are crystal clear to me.

Your colleagues must be able to follow your decisions and must be easy to understand what you are doing. It's important to be brief and concise with your commit's title and description.

Cheers,

**Comment by JPGSP** [comment]
I did a desc of the table user and I saw that the column role was duplicated.
The entity User is extended from one class  in the User bundle, reason why there are a few extra columns in the table which are not configured in the entity . I cleaned a few atributes in the entity to avoid duplicated and not extra functionality or unexpected bugs.

**Comment by DavidGarciaCat** [comment]
Did you check if the database needs an update after this? Are we keeping the same properties into the database or have they been removed?

**Comment by JPGSP** [comment]
Hey @DavidGarciaCat , after updating the entity I run the command 
"php app/console doctrine:schema:update --force"
To be sure the  database´s schema  and the entities are the same.
Afterwards I did a check in the database I could verify the changes were done in the entity are succesfully deployed in the db (it only appears one role column, per example)

**Comment by DavidGarciaCat** [comment]
Please refer to [this issue](https://github.com/JPGSP/blog/issues/24) for further details
