### ISSUE TITLE
ORM Column length for String type

### ISSUE THREAD

**Issue by DavidGarciaCat** [JPGSP/blog#4]
By default, all `@ORM/Column` annotations that are defined as `string` have been pre-set with a maximum length of 255 characters, so we have 2 potential scenarios:

**Example:**

```php
/**
 * @ORM\Column(name="column_name", type="string", length=255)
 */
```

**1) There is no need to be redundant**, so this `length=255` can be removed due this is the by-default value

**2) Keep them for future references**, just in case a potential update changes the by-default length.

Did you add it because you want to make sure that future updates won't cause a problem (option 2) or because you didn't know about it (option 1)?

**Comment by JPGSP** [comment]
I believe it appears automatically though the Symfony´s wizard. However I was not aware of the option 1. 
Updated and fixed.
